# Generated by Django 4.2.7 on 2023-12-13 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_city_customer_order_shippingaddress_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total_price', models.FloatField(default=0, verbose_name='Сумма заказа')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'Истории заказов',
            },
        ),
        migrations.CreateModel(
            name='SaveOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=400, verbose_name='Товар')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('product_price', models.FloatField(verbose_name='Цена товара')),
                ('final_price', models.FloatField(verbose_name='На сумму')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.saveorder')),
            ],
            options={
                'verbose_name': 'История заказанного товара',
                'verbose_name_plural': 'Истории заказанных товаров',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
