# Generated by Django 4.2.7 on 2023-12-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_saveorder_saveorderproducts_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(default='Серебро', max_length=50, null=True, verbose_name='Цвет/Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(default='Серебро', max_length=50, null=True, verbose_name='Цвет/Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default='Здесь скоро будит описание', null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='Здесь скоро будит описание', null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название товара'),
        ),
    ]
